"""
Django settings for mysites project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-4(-yow5w^^n9h8z44zi*10%0*w9=dxi!k=&deu=-wvij_%6-5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'manager',
    'subcribers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysites.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysites.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
#mysql 연결
DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE':'django.db.backends.mysql',
        'NAME':'mysites',
        'USER':'',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':'3306',
        'default-character-set':'utf8',
        'OPTIONS':{
            'init_command':"SET sql_mode='STRICT_TRANS_TABLES'",
            'charset':'utf8',
        },
    }
}
#아마존 AWS db연결
# DATABASES = {
#     'default': {
#         #'ENGINE': 'django.db.backends.sqlite3',
#         #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#         'ENGINE':'django.db.backends.mysql',
#         'NAME':'mysites',
#         'USER':'',
#         'PASSWORD':'',
#         'HOST':'',
#         'PORT':'3306',
#         'default-character-set':'utf8',
#         'OPTIONS':{
#             'init_command':"SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset':'utf8',
#         },
#     }
# }
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'

STATIC_ROOT='staticfiles'

# STATIC_URL='/static/'
# STATICFILES_DIRS=(
#     os.path.join(BASE_DIR,'static'),
# )
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
LOGIN_URL='mysite_login'
LOGOUT_UTL='mysite_logout'
LOGIN_REFIRECT_URL='home'

SITE_ID=1
CRISPY_TEMPLATE_PACK='bootstrap3'
# TEMPLATE_DIRS=[os.path.join(BASE_DIR,'templates')]
# #Custom template context peocessor setting
# TEMPLATE_LOADERS=(
#     'django.tamplate.loaders.filesystem.Loader',
#     'django.tamplate.loaders.app_directories.Loader',
#     'django.tamplate.loaders.eggs.Loader',
# )

LOGGING={
    'version':1,
    'disable_existing_loggers':False,
    'formatters':{
        'verbose':{
            'format':'[%(asctime)s]%(levelname)s[%(name)s:%(lineno)s]%(message)s',
            'datefmt':'%d%b%Y %H:%M:%S'
        },
    },
    'handlers':{
        'file':{
            'level':'DEBUG',
            'class':'logging.FileHandler',
            'filename':os.path.join(BASE_DIR,'logs/logfile'),
            'formatter':'verbose'
        },
    },
    'loggers':{
        'polls':{
            'handlers':['file'],
            'level':'DEBUG',
        },
        'polls.views':{
            'handlers':['file'],
            'propagate':False,
            'level':'DEBUG',
        },
    }
}

TIME=5*60
SESSION_SERIALIZER='django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
SESSION_COOKIE_AGE=TIME

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
